name: ps4-release

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ps4:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Build Environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y pacman-package-manager wget cmake git gettext smpq && \
        sudo tee -a /etc/pacman.conf > /dev/null <<TEXT
        [pacbrew]
        SigLevel = Optional TrustAll
        Server = https://pacman.mydedibox.fr/pacbrew/packages/
        TEXT
    - name: Setup pacman packages
      run: |
        sudo pacman --noconfirm -Sy && \
        sudo pacman --noconfirm -S ps4-openorbis ps4-openorbis-portlibs && \
        echo "#include <endian.h>" | sudo tee /opt/pacbrew/ps4/openorbis/include/sys/endian.h

    - name: Configure
      run: |
         cd $GITHUB_WORKSPACE
         cd pscrap
         echo "123154" >> tmdb.key
         cd ..
         mkdir cmake-build && cd cmake-build
         export OPENORBIS=/opt/pacbrew/ps4/openorbis
         cmake -G "Unix Makefiles" -DPLATFORM_PS4=ON -DCMAKE_BUILD_TYPE=Release ..

    - name: Build pplay
      run: |
         cd $GITHUB_WORKSPACE/cmake-build
         make pplay_pkg
         mv *.pkg $GITHUB_WORKSPACE

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*.pkg'
        token: ${{ secrets.GITHUB_TOKEN }}
